language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn run test
after_success:
  - yarn run semantic-release
branches:
  only:
    - master
    - dev
